require:
  - rubocop-rspec
  - rubocop-rake
  - rubocop-performance

AllCops:
  # note additional conf in spec/
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - gemfiles/*
    - lib/deprecation_collector/web/views/*.template.rb

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/ClassLength: { Max: 230 }
Metrics/MethodLength: { Max: 15 }
Metrics/AbcSize: { Max: 23 }
Metrics/CyclomaticComplexity: { Max: 9 }
Metrics/PerceivedComplexity: { Max: 9 }

RSpec/ExampleLength: { Enabled: false }
RSpec/MultipleExpectations: { Enabled: false }
RSpec/MessageSpies: { Enabled: false }
