AllCops:
  # spec/ have TargetRubyVersion: 2.6
  TargetRubyVersion: 2.4
  NewCops: enable

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/ClassLength: { Max: 200 }
Metrics/MethodLength: { Max: 15 }
Metrics/CyclomaticComplexity: { Max: 9 }
Metrics/PerceivedComplexity: { Max: 9 }
