AllCops:
  # note additional conf in spec/
  TargetRubyVersion: 2.5
  NewCops: enable
  Exclude:
    - gemfiles/*

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/ClassLength: { Max: 230 }
Metrics/MethodLength: { Max: 15 }
Metrics/AbcSize: { Max: 20}
Metrics/CyclomaticComplexity: { Max: 9 }
Metrics/PerceivedComplexity: { Max: 9 }
