name: Test
on: [push]
jobs:
  runTests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [3.2.2]
        appraisal:
          - rails_none
          - rails_6
          - rails_7
          - rails_71
        include:
          - ruby-version: 2.7.8
            appraisal: rails_71
          - ruby-version: 2.5.9
            appraisal: rails_none
    env:
      BUNDLE_WITHOUT: lint
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.appraisal }}.gemfile

    steps:
      - uses: actions/checkout@master
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rake spec
