name: Test
on: [push]
jobs:
  runTests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 3.4.1
        rails:
          - none
          - 72
          - 80
        include:
          - ruby: 2.5.9
            rails: none
          - ruby: 2.7.8
            rails: 6
          - ruby: 3.2.6
            rails: 7
          - ruby: 3.2.6
            rails: 71
          - ruby: 3.2.6
            rails: 72
    env:
      BUNDLE_WITHOUT: lint
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/rails_${{ matrix.rails }}.gemfile

    steps:
      - uses: actions/checkout@master
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Run tests
        run: |
          bundle exec rake spec
